FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       software-properties-common \
    && add-apt-repository universe \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       nginx libnginx-mod-rtmp ffmpeg openssl \
    && rm -rf /var/lib/apt/lists/*

# Diretório para HLS
RUN mkdir -p /var/www/html/hls_native

# Diretório para certificados
RUN mkdir -p /etc/nginx/certs

# Certificado autoassinado
RUN openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/selfsigned.key \
    -out /etc/nginx/certs/selfsigned.crt \
    -subj "/C=BR/ST=RN/L=Natal/O=VRLab/OU=Streaming/CN=localhost"

COPY index.html /var/www/html/
COPY nginx-vr.conf /etc/nginx/nginx.conf
COPY video.mp4 /opt/video.mp4
COPY runVR.sh /opt/run.sh
RUN chmod +x /opt/run.sh

EXPOSE 80 443 1935

CMD ["/opt/run.sh"]

